.PHONY: init
init:
	npm install

.PHONY: run
run:
	npm start

.PHONY: fmt
fmt:
	npm run fmt

.PHONY: ci/fmt
ci/fmt:
	npm run fmt.check

.PHONY: ci/lint
ci/lint:
	npm run lint

.PHONY: deploy/build
deploy/build:
	npm run build
